# =============================================================
# testing_v2.py — Threshold Sweeping dengan ChromaDB Real
# Jalankan: python testing_v2.py
# Pastikan venv aktif & database sudah terisi dataset
# =============================================================

import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

# ─── Coba import Searcher dari project, fallback ke mode offline ───
USE_REAL_DB = False
try:
    from modules.searcher import Searcher
    USE_REAL_DB = True
    print("[INFO] Searcher ditemukan — menggunakan ChromaDB real.")
except Exception as e:
    USE_REAL_DB = False
    print(f"[INFO] Tidak bisa load Searcher ({type(e).__name__}) — menggunakan similarity score offline.")

# =============================================================
# DATA: 50 pasang judul
# Format: (Judul_A, Judul_B, Label_Pakar)
# Label: 1 = Mirip, 0 = Tidak Mirip
# =============================================================
PASANG = [
    # ── INTRA-PRODI SISTEM INFORMASI (1-5) ──────────────────────
    ("RANCANG BANGUN SISTEM INVENTORY BERBASIS ANDROID MENGGUNAKAN SQLITE PADA PEDAGANG SANDAL DI PASAR TODDOPULI",
     "SISTEM INFORMASI PERSEDIAAN STOK BENIH TANAMAN MENGGUNAKAN TEKNOLOGI BARCODE DALAM STUDI KASUS KANTOR BALAI PERTANIAN TANAMAN HUTAN BPTH WILAYAH II",
     0),  # 01 — Berbeda topik (inventory sandal vs benih)
    ("SISTEM INFORMASI ANTRIAN PADA KLINIK NABILA DENTAL MENGGUNAKAN ALGORITMA FIRST COME FIRST SERVED",
     "PERANCANGAN SISTEM ANTRIAN BERBASIS ONLINE PADA JASA PRINTING MENGGUNAKAN ALGORITMA PRIORITY SCHEDULING NON PREEMPTIVE",
     1),  # 02 — MIRIP (sistem antrian)
    ("SISTEM INFORMASI MONITORING DAN ANALISIS KINERJA MITRA PENGAJAR PADA KEGIATAN VSGA KEMENTERIAN KOMUNIKASI DAN INFORMATIKA",
     "EFISIENSI DAN EFEKTIVITAS SISTEM PENGINGAT UJIAN SEMINAR PADA UIN ALAUDDIN MAKASSAR MENGGUNAKAN REAL TIME NOTIFICATION",
     0),  # 03 — Berbeda (monitoring kinerja vs pengingat ujian)
    ("PENGEMBANGAN SISTEM REKOMENDASI TEMPAT WISATA BERBASIS WEBSITE MENGGUNAKAN METODE CONSTRAINT-BASED RECOMMENDATION SYSTEM",
     "PENERAPAN ALGORITMA BOYER-MOORE PADA PENCARIAN HADIS TERINTEGRASI DALAM KAJIAN SISTEM INFORMASI BERBASIS WEBSITE",
     0),  # 04 — Berbeda (wisata vs hadis)
    ("SISTEM INFORMASI PENGELOLAAN DATA PEDAGANG PASAR STUDI KASUS DINAS PERDAGANGAN DAN PERINDUSTRIAN KABUPATEN GOWA",
     "SISTEM PENGINGAT PEMBAYARAN BULANAN DI TAHFIDZ CHILDREN EL-FATA MENGGUNAKAN ALGORITMA SCHEDULE",
     0),  # 05 — Berbeda
    # ── INTRA-PRODI TEKNIK INFORMATIKA (6-15) ───────────────────
    ("RANCANG BANGUN KEAMANAN PENGUNCI LEMARI BESI DENGAN MENGGUNAKAN FINGERPRINT BERBASIS ARDUINO UNO DENGAN NOTIFIKASI TELEGRAM",
     "PENGELOMPOKAN FOTO OTOMATIS BERDASARKAN IDENTIFIKASI WAJAH MENGGUNAKAN ALGORITMA DENSITY BASED SPATIAL CLUSTERING OF APPLICATION WITH NOISE",
     0),  # 06 — Berbeda
    ("PENGENALAN EKSPRESI WAJAH MENGGUNAKAN CONVOLUTIONAL NEURAL NETWORK CNN",
     "KLASIFIKASI TOPIK DOKUMEN SKRIPSI BERDASARKAN JUDUL DAN ABSTRAK MENGGUNAKAN METODE ENSEMBLE CLASSIFIER",
     1),  # 07 — MIRIP (klasifikasi/pengenalan ML)
    ("ANALISIS DAN IMPLEMENTASI ALGORITMA YOU ONLY LOOK ONCE DAN OTSU THRESHOLD DALAM MENDETEKSI PELAT NOMOR KENDARAAN BERMOTOR",
     "IMPLEMENTASI TEKNOLOGI COMPUTER VISION MENGGUNAKAN ALGORITMA DEEP LEARNING UNTUK MEMINIMALISIR DAMPAK RADIASI LAYAR HANDPHONE TERHADAP MATA PENGGUNA",
     1),  # 08 — MIRIP (computer vision deep learning)
    ("KLASIFIKASI FERTILITAS TELUR AYAM MENGGUNAKAN ALGORITMA YOLOV8",
     "SISTEM QUESTION ANSWERING PADA CHATBOT MENGGUNAKAN ARTIFICIAL INTELLIGENCE UNTUK MENDUKUNG SISTEM PENJAMINAN MUTU PADA PROGRAM STUDI",
     0),  # 09 — Berbeda
    ("GAME EDUKASI ANTI NARKOBA SEBAGAI ALAT ALTERNATIF DALAM MENINGKATKAN PENGETAHUAN TERHADAP NARKOBA BERBASIS ANDROID",
     "ANALISIS PENERAPAN PROGRESSIVE WEB APPLICATION PWA PADA SISTEM INFORMASI PENJUALAN KUDA DI KABUPATEN JENEPONTO",
     0),  # 10 — Berbeda
    ("PENERAPAN ALGORITMA MULTILAYER PERCEPTRON DALAM MENENTUKAN KELAYAKAN DAN KLASIFIKASI KUALITAS AIR TAMBAK PADA BUDIDAYA IKAN BANDENG DAN UDANG VANAME",
     "IMPLEMENTASI METODE ADAPTIVE PARTICLE SWARM OPTIMIZATION DALAM OPTIMASI FORMULASI PAKAN IKAN BANDENG",
     1),  # 11 — MIRIP (domain ikan bandeng + ML)
    ("RANCANG BANGUN PERINGATAN DINI BAGI PENGENDARA BERMOTOR YANG TIDAK PAKAI HELM MENGGUNAKAN YOLO",
     "PEMANFAATAN LARGE LANGUAGE MODEL UNTUK MENINGKATKAN KEMAMPUAN PEMAHAMAN PERINTAH KENDALI BERBASIS SUARA PADA PERANGKAT SMART HOME",
     0),  # 12 — Berbeda
    ("DETEKSI SERANGAN DDOS DISTRIBUTED DENIAL OF SERVICE MENGGUNAKAN METODE WAVELET DECOMPOSITION",
     "OPTIMALISASI PREDIKSI KELULUSAN MAHASISWA TEPAT WAKTU MENGGUNAKAN BINNING DAN SYNTHETIC MINORITY OVERSAMPLING TECHNIQUE SMOTE",
     0),  # 13 — Berbeda
    ("HYBRID SENTIMENT ANALYSIS TENTANG PERGANTIAN KURIKULUM PEMBELAJARAN MENGGUNAKAN ARTIFICIAL NEURAL NETWORK ANN DAN TOPIC MODELING",
     "SISTEM PEMILAHAN KUALITAS TELUR AYAM RAS MENGGUNAKAN METODE FUZZY BERBASIS INTERNET OF THINGS IOT",
     0),  # 14 — Berbeda
    ("ANALISIS SENTIMEN TERHADAP ULASAN WISATAWAN PANTAI LOSARI BERBASIS WORD EMBEDDING DAN LONG SHORT-TERM MEMORY LSTM UNTUK PENINGKATAN LAYANAN PARIWISATA",
     "PERHITUNGAN OTOMATIS UKURAN UDANG VANAME MENERAPKAN OBJECT DETECTION DENGAN CONVOLUTIONAL NEURAL NETWORK MENGGUNAKAN METODE BIDIRECTIONAL FEATURE PYRAMID NETWORK",
     0),  # 15 — Berbeda
    # ── INTRA-PRODI BIOLOGI (16-19) ─────────────────────────────
    ("PENGARUH KALOKO PAO MANGIFERA INDICA L TERHADAP AKTIVITAS HARIAN DAN PENURUNAN KADAR GLUKOSA DARAH MENCIT MUS MUSCULUS ICR JANTAN",
     "ANALISIS POLA SIDIK JARI METABOLIT SEKUNDER DAN POTENSI EKSTRAK METANOL DAUN AWAR-AWAR FICUS SEPTICA SEBAGAI ANTIKANKER",
     0),  # 16 — Berbeda (glukosa darah vs antikanker)
    ("KUANTIFIKASI DAN EVALUASI POTENSI PROBIOTIK BAKTERI ASAM LAKTAT DARI TEMPE ULAT SAGU",
     "EFEKTIVITAS BAKTERIOFAG TERHADAP PENGENDALIAN INFEKSI AEROMONAS SP PADA IKAN NILA OREOCHROMIS NILOTICUS",
     0),  # 17 — Berbeda (probiotik vs bakteriofag)
    ("ANALISIS VEGETASI TAMAN NASIONAL BANTIMURUNG BULUSARAUNG MENGGUNAKAN METODE NDVI EVI DAN SAVI",
     "ANALISIS SEBARAN TUMBUHAN INVASIF DI RESORT MALLAWA TAMAN NASIONAL BANTIMURUNG BULUSARAUNG KABUPATEN MAROS SULAWESI SELATAN",
     1),  # 18 — MIRIP (TN Bantimurung, analisis vegetasi/tumbuhan)
    ("EFEKTIVITAS EKSTRAK DAUN MIANA PLECTRANTHUS SCUTELLARIOIDES SEBAGAI PENYEMBUHAN LUKA PADA MENCIT MUS MUSCULUS ICR JANTAN SECARA IN VIVO",
     "UJI KETAHANAN TANAMAN PISANG MUSA PARADISIACA TERHADAP BAKTERI RALSTONIA SYZYGII SUBSP CELEBESENSIS YANG DIINDUKSI BAKTERI RIZOSFER PISANG",
     0),  # 19 — Berbeda
    # ── INTRA-PRODI FISIKA (20-25) ───────────────────────────────
    ("PENGARUH SALINITAS TERHADAP TOTAL KARBOHIDRAT DAN PERTUMBUHAN TANAMAN CABAI RAWIT CAPSICUM FRUTESCENS L VARIETAS SALO DUA S2 KABUPATEN ENREKANG",
     "PENGARUH SALINITAS TERHADAP KADAR PROLIN DAN KANDUNGAN AIR RELATIF CABAI RAWIT CAPSICUM FRUTESCENS L VARIETAS SALO DUA S2 KABUPATEN ENREKANG",
     1),  # 20 — MIRIP (salinitas + cabai rawit + lokasi sama)
    ("PENENTUAN CLUSTER PADA DISTRIBUSI GEMPABUMI MENGGUNAKAN METODE MINI BATCH K-MEANS STUDI KASUS PGR IV TAHUN 1900-2024",
     "STUDI SIFAT FISIS DAN MEKANIS EDIBLE FILM BERBAHAN EKSTRAK LIMBAH PATI KULIT SINGKONG DAUN KELOR DAN SERAT TEBU DENGAN PENAMBAHAN PLASTICIZER SORBITOL SEBAGAI KEMASAN RAMAH LINGKUNGAN",
     0),  # 21 — Berbeda
    ("SINTESIS DAN KARAKTERISASI EDIBLE FILM KOMBINASI EKSTRAK KULIT SALAK PATI JAGUNG DAN PLASTICIZER GLISEROL",
     "PEMANFAATAN TEMPURUNG KLUWAK SEBAGAI CARBON DOTS CDS UNTUK APLIKASI PENDETEKSI LOGAM BERAT TIMBAL PB",
     0),  # 22 — Berbeda
    ("SINTESIS DAN KARAKTERISASI CARBON DOTS CDS BERBAHAN DASAR RUMPUT LAUT MERAH DENGAN TEKNIK MICROWAVE SEBAGAI PENDETEKSI LOGAM BERAT TIMBAL PB",
     "MEMBRAN KITOSAN BERBASIS TULANG IKAN SUNU DENGAN MATRIKS PVA PEG 4000 SIO2 SEBAGAI ADSORBEN LOGAM BERAT",
     0),  # 23 — Mirip domain (logam berat) tapi beda metode
    ("SINTESIS DAN KARAKTERISASI CARBON DOTS CDS BERBAHAN DASAR CANGKANG BUAH KARET HEVEA BRASILIENSIS DENGAN TEKNIK MICROWAVE SEBAGAI PENDETEKSI ION LOGAM BERAT ARSEN AS",
     "ANALISIS KITOSAN SISIK IKAN KURISI MERAH NEMIPTERUS VIRGATUS DENGAN PENAMBAHAN TIO2 SEBAGAI ADSORBEN LOGAM BERAT PADA AIR LINDI DI TPA BATU TERANG KABUPATEN BANTAENG",
     0),  # 24 — Berbeda
    ("PENGARUH UKURAN PARTIKEL DAN BAHAN PEREKAT TERHADAP KUALITAS BIOBRIKET CAMPURAN TONGKOL JAGUNG TEMPURUNG KELAPA DAN KOTORAN SAPI",
     "PENGEMBANGAN KITOSAN BERBASIS SISIK IKAN KURISI MERAH NEMIPTERUS VIRGATUS DAN KARBON AKTIF UNTUK MENGADSORPSI LOGAM BERAT PADA AIR LINDI DARI TPA BATU TERANG KABUPATEN BANTAENG",
     0),  # 25 — Berbeda
    # ── LINTAS PRODI (26-50) ─────────────────────────────────────
    ("RANCANG BANGUN SISTEM INVENTORY BERBASIS ANDROID MENGGUNAKAN SQLITE PADA PEDAGANG SANDAL DI PASAR TODDOPULI",
     "RANCANG BANGUN KEAMANAN PENGUNCI LEMARI BESI DENGAN MENGGUNAKAN FINGERPRINT BERBASIS ARDUINO UNO DENGAN NOTIFIKASI TELEGRAM",
     0),  # 26
    ("SISTEM INFORMASI ANTRIAN PADA KLINIK NABILA DENTAL MENGGUNAKAN ALGORITMA FIRST COME FIRST SERVED",
     "PENGELOMPOKAN FOTO OTOMATIS BERDASARKAN IDENTIFIKASI WAJAH MENGGUNAKAN ALGORITMA DENSITY BASED SPATIAL CLUSTERING OF APPLICATION WITH NOISE",
     0),  # 27
    ("SISTEM INFORMASI MONITORING DAN ANALISIS KINERJA MITRA PENGAJAR PADA KEGIATAN VSGA KEMENTERIAN KOMUNIKASI DAN INFORMATIKA",
     "PENGENALAN EKSPRESI WAJAH MENGGUNAKAN CONVOLUTIONAL NEURAL NETWORK CNN",
     0),  # 28
    ("PENGEMBANGAN SISTEM REKOMENDASI TEMPAT WISATA BERBASIS WEBSITE MENGGUNAKAN METODE CONSTRAINT-BASED RECOMMENDATION SYSTEM",
     "KLASIFIKASI TOPIK DOKUMEN SKRIPSI BERDASARKAN JUDUL DAN ABSTRAK MENGGUNAKAN METODE ENSEMBLE CLASSIFIER",
     0),  # 29
    ("EFISIENSI DAN EFEKTIVITAS SISTEM PENGINGAT UJIAN SEMINAR PADA UIN ALAUDDIN MAKASSAR MENGGUNAKAN REAL TIME NOTIFICATION",
     "ANALISIS DAN IMPLEMENTASI ALGORITMA YOU ONLY LOOK ONCE DAN OTSU THRESHOLD DALAM MENDETEKSI PELAT NOMOR KENDARAAN BERMOTOR",
     0),  # 30
    ("RANCANG BANGUN SISTEM INVENTORY BERBASIS ANDROID MENGGUNAKAN SQLITE PADA PEDAGANG SANDAL DI PASAR TODDOPULI",
     "PENGARUH KALOKO PAO MANGIFERA INDICA L TERHADAP AKTIVITAS HARIAN DAN PENURUNAN KADAR GLUKOSA DARAH MENCIT MUS MUSCULUS ICR JANTAN",
     0),  # 31
    ("SISTEM INFORMASI ANTRIAN PADA KLINIK NABILA DENTAL MENGGUNAKAN ALGORITMA FIRST COME FIRST SERVED",
     "KUANTIFIKASI DAN EVALUASI POTENSI PROBIOTIK BAKTERI ASAM LAKTAT DARI TEMPE ULAT SAGU",
     0),  # 32
    ("SISTEM INFORMASI MONITORING DAN ANALISIS KINERJA MITRA PENGAJAR",
     "ANALISIS VEGETASI TAMAN NASIONAL BANTIMURUNG BULUSARAUNG MENGGUNAKAN METODE NDVI EVI DAN SAVI",
     0),  # 33
    ("PENGEMBANGAN SISTEM REKOMENDASI TEMPAT WISATA BERBASIS WEBSITE",
     "EFEKTIVITAS EKSTRAK DAUN MIANA SEBAGAI PENYEMBUHAN LUKA PADA MENCIT ICR JANTAN SECARA IN VIVO",
     0),  # 34
    ("SISTEM INFORMASI PENGELOLAAN DATA PEDAGANG PASAR",
     "PENGARUH SALINITAS TERHADAP TOTAL KARBOHIDRAT DAN PERTUMBUHAN TANAMAN CABAI RAWIT",
     0),  # 35
    ("RANCANG BANGUN KEAMANAN PENGUNCI LEMARI BESI FINGERPRINT ARDUINO UNO NOTIFIKASI TELEGRAM",
     "PENENTUAN CLUSTER PADA DISTRIBUSI GEMPABUMI MENGGUNAKAN METODE MINI BATCH K-MEANS",
     0),  # 36
    ("PENGENALAN EKSPRESI WAJAH MENGGUNAKAN CONVOLUTIONAL NEURAL NETWORK CNN",
     "SINTESIS DAN KARAKTERISASI EDIBLE FILM KOMBINASI EKSTRAK KULIT SALAK PATI JAGUNG DAN PLASTICIZER GLISEROL",
     0),  # 37
    ("ANALISIS DAN IMPLEMENTASI ALGORITMA YOU ONLY LOOK ONCE DALAM MENDETEKSI PELAT NOMOR KENDARAAN BERMOTOR",
     "SINTESIS DAN KARAKTERISASI CARBON DOTS CDS BERBAHAN DASAR RUMPUT LAUT MERAH DENGAN TEKNIK MICROWAVE",
     0),  # 38
    ("KLASIFIKASI FERTILITAS TELUR AYAM MENGGUNAKAN ALGORITMA YOLOV8",
     "SINTESIS DAN KARAKTERISASI CARBON DOTS CDS BERBAHAN DASAR CANGKANG BUAH KARET DENGAN TEKNIK MICROWAVE",
     0),  # 39
    ("GAME EDUKASI ANTI NARKOBA BERBASIS ANDROID",
     "PENGARUH UKURAN PARTIKEL DAN BAHAN PEREKAT TERHADAP KUALITAS BIOBRIKET CAMPURAN TONGKOL JAGUNG TEMPURUNG KELAPA",
     0),  # 40
    ("PENERAPAN ALGORITMA MULTILAYER PERCEPTRON DALAM KLASIFIKASI KUALITAS AIR TAMBAK BUDIDAYA IKAN BANDENG",
     "PENGARUH KALOKO PAO MANGIFERA INDICA L TERHADAP AKTIVITAS HARIAN DAN KADAR GLUKOSA DARAH MENCIT ICR JANTAN",
     0),  # 41
    ("RANCANG BANGUN PERINGATAN DINI BAGI PENGENDARA BERMOTOR YANG TIDAK PAKAI HELM MENGGUNAKAN YOLO",
     "KUANTIFIKASI DAN EVALUASI POTENSI PROBIOTIK BAKTERI ASAM LAKTAT DARI TEMPE ULAT SAGU",
     0),  # 42
    ("DETEKSI SERANGAN DDOS MENGGUNAKAN METODE WAVELET DECOMPOSITION",
     "ANALISIS VEGETASI TAMAN NASIONAL BANTIMURUNG BULUSARAUNG MENGGUNAKAN METODE NDVI EVI DAN SAVI",
     0),  # 43
    ("HYBRID SENTIMENT ANALYSIS PERGANTIAN KURIKULUM MENGGUNAKAN ARTIFICIAL NEURAL NETWORK DAN TOPIC MODELING",
     "EFEKTIVITAS EKSTRAK DAUN MIANA SEBAGAI PENYEMBUHAN LUKA PADA MENCIT ICR JANTAN SECARA IN VIVO",
     0),  # 44
    ("ANALISIS SENTIMEN ULASAN WISATAWAN PANTAI LOSARI BERBASIS WORD EMBEDDING DAN LSTM",
     "PENGARUH SALINITAS TERHADAP KADAR PROLIN DAN KANDUNGAN AIR RELATIF CABAI RAWIT VARIETAS SALO DUA",
     0),  # 45
    ("SISTEM INFORMASI INVENTORY BERBASIS ANDROID PEDAGANG PASAR TODDOPULI",
     "PENENTUAN CLUSTER DISTRIBUSI GEMPABUMI MENGGUNAKAN METODE MINI BATCH K-MEANS",
     0),  # 46
    ("SISTEM INFORMASI ANTRIAN KLINIK NABILA DENTAL ALGORITMA FIRST COME FIRST SERVED",
     "SINTESIS DAN KARAKTERISASI EDIBLE FILM KOMBINASI EKSTRAK KULIT SALAK PATI JAGUNG PLASTICIZER GLISEROL",
     0),  # 47
    ("PENGEMBANGAN SISTEM REKOMENDASI TEMPAT WISATA BERBASIS WEBSITE",
     "SINTESIS DAN KARAKTERISASI CARBON DOTS BERBAHAN DASAR CANGKANG BUAH KARET HEVEA BRASILIENSIS TEKNIK MICROWAVE",
     0),  # 48
    ("PENGENALAN EKSPRESI WAJAH MENGGUNAKAN CNN",
     "PENGARUH UKURAN PARTIKEL DAN BAHAN PEREKAT KUALITAS BIOBRIKET CAMPURAN TONGKOL JAGUNG TEMPURUNG KELAPA KOTORAN SAPI",
     0),  # 49
    ("KLASIFIKASI FERTILITAS TELUR AYAM YOLOV8",
     "PENGEMBANGAN KITOSAN BERBASIS SISIK IKAN KURISI MERAH NEMIPTERUS VIRGATUS KARBON AKTIF ADSORPSI LOGAM BERAT",
     0),  # 50
]

true_labels = [p[2] for p in PASANG]
judul_a_list = [p[0] for p in PASANG]
judul_b_list = [p[1] for p in PASANG]

print(f"Total pasang : {len(PASANG)}")
print(f"Label Mirip  : {sum(true_labels)} pasang")
print(f"Label Tdk Mirip: {len(true_labels) - sum(true_labels)} pasang")
print()

# =============================================================
# AMBIL SIMILARITY SCORE
# Mode 1: Query real ke ChromaDB via Searcher
# Mode 2: Offline (similarity_scores hardcoded dari ground_truth)
# =============================================================
if USE_REAL_DB:
    print("Menghitung similarity score dari ChromaDB (ini mungkin butuh beberapa menit)...")
    searcher = Searcher()
    similarity_scores = []
    TOP_N = 100

    for i, (judul_a, judul_b, _) in enumerate(PASANG, 1):
        results = searcher.search(judul_a, top_n=TOP_N)
        score = 0.0
        for r in results:
            if r['judul'].strip().lower() == judul_b.strip().lower():
                score = r['similarity']
                break
        similarity_scores.append(score)
        print(f"  [{i:02d}/50] Skor: {score:.4f}")

    print("\n[INFO] Similarity scores dari ChromaDB berhasil diambil.")

else:
    # ── Offline fallback (dari ground_truth_LENGKAP.xlsx) ────────
    # Ganti nilai ini dengan output similarity score dari ChromaDB-mu
    similarity_scores = [
        0.0000, 0.5870, 0.4967, 0.5018, 0.4367,
        0.0000, 0.0000, 0.4472, 0.0000, 0.0000,
        0.5127, 0.4545, 0.0000, 0.0000, 0.0000,
        0.0000, 0.4466, 0.5749, 0.0000, 0.8127,
        0.0000, 0.4375, 0.4340, 0.4659, 0.4564,
        0.4129, 0.4519, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
    ]
    print("[INFO] Menggunakan similarity scores offline dari ground_truth_LENGKAP.xlsx\n")

# =============================================================
# THRESHOLD SWEEPING
# =============================================================
print("=" * 68)
print(f"{'Threshold':>10} {'Precision':>10} {'Recall':>10} {'F1-Score':>10} {'Accuracy':>10}")
print("=" * 68)

thresholds = np.round(np.arange(0.10, 0.91, 0.05), 2)
best = {"f1": 0.0, "threshold": 0.0}

# Hitung dulu f1 max untuk marker
f1_list = [f1_score(true_labels, [1 if s >= t else 0 for s in similarity_scores], zero_division=0)
           for t in thresholds]
max_f1 = max(f1_list)

for t, f1_val in zip(thresholds, f1_list):
    pred = [1 if s >= t else 0 for s in similarity_scores]
    p   = precision_score(true_labels, pred, zero_division=0)
    r   = recall_score(true_labels, pred, zero_division=0)
    acc = accuracy_score(true_labels, pred)
    marker = " ← OPTIMAL" if abs(f1_val - max_f1) < 1e-9 else ""
    print(f"{t:>10.2f} {p*100:>9.2f}% {r*100:>9.2f}% {f1_val*100:>9.2f}% {acc*100:>9.2f}%{marker}")

    if f1_val > best["f1"] or (f1_val == best["f1"] and t < best["threshold"]):
        pred_best = pred
        best = {
            "threshold": t, "precision": p, "recall": r,
            "f1": f1_val, "accuracy": acc,
            "TP": sum(1 for a, b in zip(true_labels, pred) if a==1 and b==1),
            "FP": sum(1 for a, b in zip(true_labels, pred) if a==0 and b==1),
            "FN": sum(1 for a, b in zip(true_labels, pred) if a==1 and b==0),
            "TN": sum(1 for a, b in zip(true_labels, pred) if a==0 and b==0),
        }

# =============================================================
# DETAIL PER PASANG (Threshold Optimal)
# =============================================================
print("\n" + "=" * 68)
print(f"DETAIL HASIL (Threshold Optimal = {best['threshold']})")
print("=" * 68)
for i, (ja, jb, label) in enumerate(PASANG, 1):
    pred = 1 if similarity_scores[i-1] >= best["threshold"] else 0
    status = "✓" if pred == label else "✗"
    kategori = ""
    if pred == 1 and label == 1: kategori = "TP"
    elif pred == 1 and label == 0: kategori = "FP"
    elif pred == 0 and label == 1: kategori = "FN"
    else: kategori = "TN"
    print(f"{i:2d}. {status} [{kategori}] Skor={similarity_scores[i-1]:.4f} | Pakar={label} | Prediksi={pred}")
    print(f"    A: {ja[:85]}")
    print(f"    B: {jb[:85]}")

# =============================================================
# HASIL AKHIR
# =============================================================
print("\n" + "=" * 68)
print(f"  THRESHOLD OPTIMAL : {best['threshold']}")
print(f"  Precision         : {best['precision']*100:.2f}%")
print(f"  Recall            : {best['recall']*100:.2f}%")
print(f"  F1-Score          : {best['f1']*100:.2f}%")
print(f"  Accuracy          : {best['accuracy']*100:.2f}%")
print(f"\n  Confusion Matrix  :")
print(f"  TP={best['TP']}  FP={best['FP']}  FN={best['FN']}  TN={best['TN']}")
print("=" * 68)
